### ISSUE TITLE
Analyse der Problematik bei den möglichen Customer

### ISSUE THREAD

**Issue by NicolasSchlaepfer** [Luke-Albright/SmartHome_Gruppe_D#1]
Was ist der grösste Pain im Bereich Health?
Welche Hürden gibt es zu Hause?
Was hält die Leute davon ab, gesünder zu leben?

**Comment by Sonam-M** [comment]
Issue ist erledigt. User Journeys erstellt

**Comment by Sonam-M** [comment]
abgeschlossen
